version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - g-k
  assignees:
  - g-k
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    timezone: UCT
  open-pull-requests-limit: 99
  reviewers:
  - g-k
  assignees:
  - g-k
